export const commonTableScheme = `
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL,
`;

export const idColumns = `id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY`;

export const datesColumns = `createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL`;
